### ISSUE TITLE
Narcissus mini-settings blocks Dragonriding Customization UI

### ISSUE THREAD

**Issue by Ketrel** [Peterodox/Narcissus#12]
The mini settings popup thing that shows when you hover in the bottom left corner also shows when you're in the Dragonriding Customization UI and it blocks the Reset and Cancel buttons.  See attached image

![image](https://github.com/Peterodox/Narcissus/assets/1002607/83c3004b-3799-4582-8e46-08a7ca904db1)

**Comment by Peterodox** [comment]
Thanks for the report. It'll be fixed in this weekend's update.
