### ISSUE TITLE
Quick swap tinker gems for multiple specs/roles ie tank/heal/dps

### ISSUE THREAD

**Issue by cruzanstx** [Peterodox/Narcissus#15]
Love the addon works great in wow remix. could you create a way to save a loadout of tinkers/gems that you can swap whenever you switch specs? I play druid and would like to swap healer/dps/tank gems n tinkers out. Thanks for your hard work!

**Comment by DJScias** [comment]
Pretty sure something like this is in the works:
https://x.com/Peterodox/status/1794223285976367171

![GOZckS3W4AA0E-T](https://github.com/Peterodox/Narcissus/assets/439655/8ab17ba2-7fc7-4b87-b1ea-34cd1cc35710)

**Comment by Peterodox** [comment]
Feature delivered :)
