### ISSUE TITLE
2 minimap icons

### ISSUE THREAD

**Issue by Rinkashirukito** [Peterodox/Narcissus#27]
Since 1.7.3 (or 1.7.2 i think i skipped that one) there are now 2 minimap icons for narcissus

The "old" icon with the stylized dropdown and the icon which is chosen in the settings, and a new one that looks more like a default minimap icon with a "regular" wow dropdown menu and the icon has the typical minimap addon-button border. When disabling the minimap icon in the settings, only "old" icon vanishes, the new one stays no matter what.

I dont use any addons that handles minimap addon buttons

**Comment by Ketrel** [comment]
I do use (and maintain) an addon that handles minimap buttons (specifically https://github.com/Ketrel/MinimapButtonFrame-Redux ), and I also am getting two separate buttons.

![image](https://github.com/user-attachments/assets/b7bd4435-7218-4b76-a724-11fcf5c730a9)

**Comment by Peterodox** [comment]
Hi!
It has been fixed in v1.7.3-b
