### ISSUE TITLE
Talet Tree Viewer scaling

### ISSUE THREAD

**Issue by n0cks** [Peterodox/Narcissus#3]
Checking the `TalentTree.lua` file, it seems the base size of the Talent Tree (buttons, width, etc) is always a static size, making it hard to be used with higher resolution monitors.

Is there any chance a Scaling option could be added to this feature?

**Comment by Peterodox** [comment]
To achieve pixel-perfect the textures' sizes in pixels are all constant. (e.g. trait nodes are 32x32 px), so yes it can be hard to precisely control your cursor on 4K+ monitors.
I plan to make a high-rez version. Could you send me a screenshot with Narcissus talent tree in it, so I can decide how large should I make them?  (scaled by 1.25x or 1.5x)

**Comment by jperezruiz** [comment]
Hi! I'm also interested in this :) , I attach a screenshot on a 34' ultrawide 1440p
![Captura](https://user-images.githubusercontent.com/11233351/201371849-7c462083-2869-4d0e-a319-3bb37b82dd49.PNG)

**Comment by Peterodox** [comment]
> Hi! I'm also interested in this :) , I attach a screenshot on a 34' ultrawide 1440p ![Captura](https://user-images.githubusercontent.com/11233351/201371849-7c462083-2869-4d0e-a319-3bb37b82dd49.PNG)

Come on I'm using a standard 2K monitor! It's fine on 1440p, right?
The more imminent issue is the overlapping frames here! Is this ElvUI Windtools? I think I just saw a similar issue on Tukui's discord server.

**Comment by n0cks** [comment]
Sorry for the late reply.
I believe it's seen like that on my monitor too, 34" ultrawide on 3440x1440
Bought it for work... but I've always had issues with UI in wow because of the weird scaling 😆 
![image](https://user-images.githubusercontent.com/9072578/201412794-216fe5ea-6a21-4d13-b119-8093d1849830.png)

**Comment by jperezruiz** [comment]
> > Hi! I'm also interested in this :) , I attach a screenshot on a 34' ultrawide 1440p ![Captura](https://user-images.githubusercontent.com/11233351/201371849-7c462083-2869-4d0e-a319-3bb37b82dd49.PNG)
> 
> Come on I'm using a standard 2K monitor! It's fine on 1440p, right? The more imminent issue is the overlapping frames here! Is this ElvUI Windtools? I think I just saw a similar issue on Tukui's discord server.

Is something subjective :) for me, with the 34' looks small, for others may be enough.

Regarding the overlapping frames, yes, it is ElvUI Windtools, but it doesn't bother me, if I click in the background of the elvui, it is brought to the front
![image](https://user-images.githubusercontent.com/11233351/201442909-c059415f-8e33-48b9-8260-4b1cf961ba13.png)
Also, it is impossible to take in account every possible UI (I'm ussing ElvUI + Gen UI + Wind tools).
A possible solution would be putting a close button at the right top corner or to make it draggable (lot of work I suppose).

The idea of showing the talent tree right with the character info is fantastic, also to be able to see the talents when inspecting other players. 

Regarding the issue with the size of the icons, if you can provide both, 1.25 and 1.5 it would be awesome, with a slider to choose, I'm using 2k but I suppose there are people using 4k.

**Comment by Peterodox** [comment]
@n0cks @jperezruiz 
Thanks for providing the screenshots! I'll make a larger version but it won't be included in the next update. I'm making some other stuff right now  :)

**Comment by n0cks** [comment]
Thanks a lot. Keep up the great work!

**Comment by jperezruiz** [comment]
Thank you very much!

**Comment by blaslume** [comment]
> 
**### local BUTTON_PIXEL_SIZE = 32;       **x2  64**
l### ocal ICON_PIXEL_SIZE = 24;         **x2  48****
local FONT_PIXEL_SIZE = 16;
local DISTANCE_UNIT = 300;  --600    --neighboring node distance 600
local PADDING = 1;
local HEADER_SIZE;
local SECTOR_WIDTH = 11;    --the width of each tab (spec talent, class talent). unit is button wdith.

**### local BUTTON_SIZE = 32;            **x2  64****
local BUTTON_SIZE_HALF = BUTTON_SIZE * 0.5;
local BRANCH_WEIGHT = 1;
**### local ICON_SIZE = 24;                **x2  48****
local FONT_HEIGHT = 16;
local PIXEL = 1;



check this 4 changes, do it manuiali meanwhile the owner dont make a solution it works for me

**Comment by Peterodox** [comment]
Hi! I've added this option. You might need to scroll down a bit to see it.
![BiggerUI](https://user-images.githubusercontent.com/49627468/204952558-fca9aa0a-7024-4c5a-a009-2df075105af6.jpg)

**Comment by jperezruiz** [comment]
Much better! thank you!
