### ISSUE TITLE
Narcissus achievement panel cannot replace the official by default.

### ISSUE THREAD

**Issue by xanahopper** [Peterodox/Narcissus#4]
Narcissus achievement panel cannot replace the official by default. If my memory is correct, it can replace and show achievement

**Comment by Peterodox** [comment]
Hi! I've temporarily removed this option due to the "[addon] has been blocked from an action only available to the Blizzard UI" error it can cause.

**Comment by xanahopper** [comment]
Sad, is there any solution for now?

**Comment by Peterodox** [comment]
No workaround. We'll have to wait until Blizzard fixes this :(
[https://github.com/Stanzilla/WoWUIBugs/issues/341](url)
