### ISSUE TITLE
ProjectAzilroka's Square Minimap Buttons breaks minimap button popup

### ISSUE THREAD

**Issue by branpg** [Peterodox/Narcissus#5]
First of all i love the addon. I recently changed all my UI and startes using ProkectAzilroka to pick up all the addon minimap buttons and detected this behaviour. 
Background and menu elements are correct, but text are not where it should. I find it hard to explain, but i hope this image clarifies this a little:
![image](https://github.com/Peterodox/Narcissus/assets/25660904/e5e19cc1-a2ef-47ca-986f-0ceec3753d43)

**Comment by Peterodox** [comment]
Hello!
Go to Narcissus Settings - Minimap Button, enable "Unaffected By Other Addons" then /reload.
Tips: Holding the Shift key while dragging the Narcissus minimap button can detach it from the minimap.

![MinimapButtonIndependent](https://github.com/Peterodox/Narcissus/assets/49627468/945886f6-92f1-4648-998d-f56c695f30d5)
