### ISSUE TITLE
Marksmanship Hunter Amirdrassil Tier Set Correction

### ISSUE THREAD

**Issue by AbelardTullus** [Peterodox/Narcissus#8]
Hey,

Just wanted to point out that the class set on the character sheet still lists the old spell effect instead of the current one before the rework during the PTR. Currently it's `{422876, 422877}` when it needs to be `{431168, 431172}`. Not a biggy of course, but still wanted to point it out.

**Comment by Peterodox** [comment]
Thanks for the info. We'll be using GetSetBonusesForSpecializationByItemID API so we only need to update the item IDs in the future.
